# Project
version=5.1.1
java_version=21

# Metadata
mod_name=YungsBetterMineshafts
mod_full_name=YUNG's Better Mineshafts
mod_id=bettermineshafts
mod_author=YUNGNICKYOUNG
mod_description=The long-awaited and much-needed abandoned mineshaft overhaul!
mod_credits=Thanks so much to all my patrons!
license=LGPLv3
maven_group=com.yungnickyoung.minecraft.bettermineshafts
mc_version=1.21.5
mc_version_range=[1.21.5, 1.22)
mc_version_range_fabric=>=1.21.5
parchment_minecraft=1.21
parchment_version=2024.06.23

# CurseForge/Modrinth Publishing
curseforgegradle_version=1.1.15
compatible_versions=1.21.5
curseforge_project_id_forge=389665
curseforge_project_id_fabric=373591
curseforge_project_id_neoforge=1015096
modrinth_project_id=HjmxVlSr
debug_publish=true

# Common
yungsapi_version=5.1.4

# Forge
forge_version=55.0.3
forge_loader_version_range=[55,)

# Fabric
fabric_version=0.119.6
fabric_loader_version=0.16.11
clothconfig_version_fabric=18.0.145
modmenu_version_fabric=14.0.0-rc.2

# NeoForge
neoforge_version=21.5.21-beta
neoforge_version_range=[21.5.0,)
neoforge_loader_version_range=[4,)

# Credentials for publishing. Gets overwritten with global gradle.properties.
curseforgeApiKey=""
modrinthToken=""

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false